apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "edi-adapter"
  namespace: "helsemelding"
  labels:
    "team": "helsemelding"
  annotations:
    texas.nais.io/enabled: "true"
spec:
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  ingresses:
    - "https://edi-adapter.intern.dev.nav.no"
  filesFrom:
    - secret: helsemelding-nhn-edi
      mountPath: /var/run/secrets/helsemelding-nhn-edi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvtokt
        mountPath: /secret/serviceuser
  accessPolicy:
    outbound:
      external:
        - host: helseid-sts.test.nhn.no
        - host: api.tjener.test.melding.nhn.no
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: state-service
          cluster: dev-gcp
  env:
    - name: NHN_BASE_URL
      value: "https://api.tjener.test.melding.nhn.no"
    - name: NHN_KEYPAIR_PATH
      value: "/var/run/secrets/helsemelding-nhn-edi/keypair-jwk"
    - name: NHN_TOKEN_ENDPOINT
      value: "https://helseid-sts.test.nhn.no/connect/token"
    - name: NHN_CLIENT_KEY_ID
      value: "q8u2jGS1qeISMWH2avSwJ56O-ULRPDkl64nJ4sSCJBk"
    - name: NHN_CLIENT_ID
      value: "29884a6b-ea86-4b20-978e-4986a1833e56"
    - name: NHN_CLIENT_AUDIENCE
      value: "https://helseid-sts.test.nhn.no"
    - name: NHN_CLIENT_SCOPE
      value: "nhn:msh/api"
    - name: NHN_CLIENT_GRANT_TYPE
      value: "client_credentials"
    - name: NHN_CLIENT_ASSERTION_TYPE
      value: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
